package com.mainframe.generator.codegen.generator;

import java.io.IOException;
import java.nio.file.Path;

import com.mainframe.generator.codegen.model.core.context.GeneratorConfig;
import com.mainframe.generator.codegen.util.FileWriteUtil;
import com.mainframe.generator.codegen.util.NamingUtil;

/**
 * Generates runtime utility classes and the main application.
 */
public class RuntimeGenerator {

    private static final String BASE_PACKAGE = "com.mainframe";
    private final GeneratorConfig config;

    /**
     * Creates a new RuntimeGenerator.
     *
     * @param config the generator configuration
     */
    public RuntimeGenerator(GeneratorConfig config) {
        this.config = config;
    }

    /**
     * Generates runtime utility classes.
     *
     * @param projectDir the project directory
     * @throws IOException if file writing fails
     */
    public void generate(Path projectDir) throws IOException {
        // EbcdicUtils is generated by SerdeGenerator
    }

    /**
     * Generates the Spring Boot main application class.
     *
     * @param projectDir the project directory
     * @throws IOException if file writing fails
     */
    public void generateMainApplication(Path projectDir) throws IOException {
        String className = NamingUtil.toPascalCase(config.getServiceName()) + "Application";

        String content = """
                package %s;

                import org.springframework.boot.SpringApplication;
                import org.springframework.boot.autoconfigure.SpringBootApplication;

                /**
                 * Main Spring Boot application class.
                 *
                 * Service: %s
                 */
                @SpringBootApplication
                public class %s {

                    /**
                     * Application entry point.
                     *
                     * @param args command line arguments
                     */
                    public static void main(String[] args) {
                        SpringApplication.run(%s.class, args);
                    }
                }
                """.formatted(BASE_PACKAGE, config.getServiceName(), className, className);

        Path file = projectDir.resolve("src/main/java/com/mainframe/" + className + ".java");
        FileWriteUtil.safeWriteString(file, content);
    }
}
